// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type OperationalTime struct {
	ID              int64          `json:"id"`
	OpeningTime     string         `json:"opening_time"`
	ClosingTime     string         `json:"closing_time"`
	OperationalDays string         `json:"operational_days"`
	OffDays         sql.NullString `json:"off_days"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
}

type Promo struct {
	ID               int64     `json:"id"`
	PromoName        string    `json:"promo_name"`
	StoreID          int64     `json:"store_id"`
	PromoCode        string    `json:"promo_code"`
	PromoDescription string    `json:"promo_description"`
	Quantity         int64     `json:"quantity"`
	StartAt          int64     `json:"start_at"`
	ExpiredAt        int64     `json:"expired_at"`
	IsActive         bool      `json:"is_active"`
	CreatedBy        int64     `json:"created_by"`
	CreatedAt        time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       int64     `json:"user_id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Store struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Address       string    `json:"address"`
	Description   string    `json:"description"`
	PhoneNumber   int64     `json:"phone_number"`
	OperationalID int64     `json:"operational_id"`
	IsActive      bool      `json:"is_active"`
	CreatedAt     time.Time `json:"created_at"`
}

type User struct {
	ID                int64          `json:"id"`
	Email             string         `json:"email"`
	Name              string         `json:"name"`
	Username          string         `json:"username"`
	Password          string         `json:"password"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	PhoneNumber       int64          `json:"phone_number"`
	DeviceToken       sql.NullString `json:"device_token"`
	Lang              sql.NullString `json:"lang"`
	Avatar            sql.NullString `json:"avatar"`
	UserLevel         sql.NullString `json:"user_level"`
	IsActive          bool           `json:"is_active"`
	CreatedAt         time.Time      `json:"created_at"`
}
